export const REQUEST_GET_PERMISSIONS = "REQUEST_GET_PERMISSIONS";
export const SUCCESS_GET_ADMIN_PERMISSIONS = "SUCCESS_GET_ADMIN_PERMISSIONS";
export const FAILURE_GET_ADMIN_PERMISSIONS = "FAILURE_GET_ADMIN_PERMISSIONS";

export const REQUEST_GET_USER_DATA = "REQUEST_GET_PERMISSIONS";
export const SUCCESS_GET_USER_DATA = "SUCCESS_GET_ADMIN_PERMISSIONS";
export const FAILURE_GET_USER_DATA = "FAILURE_GET_ADMIN_PERMISSIONS";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAILURE_LOGIN = "FAILURE_LOGIN";

export const REQUEST_GET_QUESTION_ACTION = "REQUEST_GET_QUESTION_ACTION";
export const SUCCESS_GET_QUESTION_ACTION = "SUCCESS_GET_QUESTION_ACTION";
export const FAILURE_GET_QUESTION_ACTION = "FAILURE_GET_QUESTION_ACTION";

export const SUCCESS_GET_QUESTION_OPTIONS_ACTION = "SUCCESS_GET_QUESTION_OPTIONS_ACTION";
export const FAILURE_GET_QUESTION_OPTIONS_ACTION = "FAILURE_GET_QUESTION_OPTIONS_ACTION";

export const REQUEST_START_TEST = "REQUEST_START_TEST";
export const SUCCES_START_TEST = "SUCCES_START_TEST";
export const FAILURE_START_TEST = "FAILURE_START_TEST";

export const REQUEST_TIMER = "REQUEST_TIMER";
export const TIMER_START = "TIMER_START";
export const TIMER_STOP = "TIMER_STOP";

export const REQUEST_SET_LANGUAGE = "REQUEST_SET_LANGUAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";

export const START_TEST = "START_TEST";
export const END_TEST = "END_TEST";